const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    price: 399,
    publishedYear: 1925,
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    price: 499,
    publishedYear: 1960,
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    price: 349,
    publishedYear: 1949,
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    price: 299,
    publishedYear: 1813,
  },
  {
    id: 5,
    title: "Moby Dick",
    author: "Herman Melville",
    genre: "Adventure",
    price: 399,
    publishedYear: 1851,
  },
  {
    id: 6,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
    price: 459,
    publishedYear: 1951,
  },
  {
    id: 7,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    price: 599,
    publishedYear: 1937,
  },
  {
    id: 8,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Sci-Fi",
    price: 329,
    publishedYear: 1953,
  },
  {
    id: 9,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    genre: "Classic",
    price: 399,
    publishedYear: 1847,
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    price: 899,
    publishedYear: 1954,
  },
  {
    id: 11,
    title: "Animal Farm",
    author: "George Orwell",
    genre: "Satire",
    price: 299,
    publishedYear: 1945,
  },
  {
    id: 12,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Philosophical",
    price: 399,
    publishedYear: 1988,
  },
  {
    id: 13,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    price: 359,
    publishedYear: 1932,
  },
  {
    id: 14,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    genre: "Drama",
    price: 499,
    publishedYear: 2003,
  },
  {
    id: 15,
    title: "The Da Vinci Code",
    author: "Dan Brown",
    genre: "Thriller",
    price: 599,
    publishedYear: 2003,
  },
  {
    id: 16,
    title: "The Book Thief",
    author: "Markus Zusak",
    genre: "Historical",
    price: 459,
    publishedYear: 2005,
  },
  {
    id: 17,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Sci-Fi",
    price: 449,
    publishedYear: 2008,
  },
  {
    id: 18,
    title: "Twilight",
    author: "Stephenie Meyer",
    genre: "Fantasy",
    price: 399,
    publishedYear: 2005,
  },
  {
    id: 19,
    title: "The Fault in Our Stars",
    author: "John Green",
    genre: "Romance",
    price: 359,
    publishedYear: 2012,
  },
  {
    id: 20,
    title: "Gone Girl",
    author: "Gillian Flynn",
    genre: "Thriller",
    price: 429,
    publishedYear: 2012,
  },
  {
    id: 21,
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    genre: "Thriller",
    price: 499,
    publishedYear: 2015,
  },
  {
    id: 22,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Psychological",
    price: 449,
    publishedYear: 2019,
  },
  {
    id: 23,
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    price: 379,
    publishedYear: 2018,
  },
  {
    id: 24,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-help",
    price: 499,
    publishedYear: 2018,
  },
  {
    id: 25,
    title: "Deep Work",
    author: "Cal Newport",
    genre: "Self-help",
    price: 429,
    publishedYear: 2016,
  },
  {
    id: 26,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "History",
    price: 599,
    publishedYear: 2011,
  },
  {
    id: 27,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    genre: "Motivational",
    price: 349,
    publishedYear: 1937,
  },
  {
    id: 28,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    genre: "Finance",
    price: 399,
    publishedYear: 1997,
  },
  {
    id: 29,
    title: "The Power of Habit",
    author: "Charles Duhigg",
    genre: "Self-help",
    price: 379,
    publishedYear: 2012,
  },
  {
    id: 30,
    title: "Ikigai",
    author: "Héctor García",
    genre: "Philosophy",
    price: 299,
    publishedYear: 2016,
  },
];

export default books;
